services:
  redis:
    image: redis:7.4.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.redis:/redis

  ollama-server:
    image: ollama/ollama:latest
    pull_policy: always
    container_name: ollama-server
    restart: on-failure
    volumes:
      - ~/.ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=1h
    healthcheck:
      test: "curl -f http://localhost:11434"

  bot-producer:
    build: .
    container_name: ollama-tg
    pull_policy: always
    restart: on-failure
    depends_on:
      - redis
    env_file:
      - ./.env
    environment:
      - REDIS_HOST=redis
    entrypoint: [ "uv", "run", "telellm/main.py" ]

  server-consumer:
    build: .
    container_name: ollama-consumer
    pull_policy: always
    restart: on-failure
    depends_on:
      - ollama-server
      - redis
    env_file:
      - ./.env
    environment:
      - OLLAMA_HOST=ollama-server
      - REDIS_HOST=redis
    entrypoint: [ "uv", "run", "telellm/consumer.py" ]
