apiVersion: batch/v1
kind: CronJob
metadata:
  name: ollama-model-updater
spec:
  schedule: "0 1 * * 0" # Run weekly at 1:00 AM on Sunday
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: model-updater
              image: curlimages/curl:latest
              command:
                - /bin/sh
                - -c
                - |
                  curl -X POST http://ollama-server:11434/api/pull -d '{"name":"llama3.2"}'
          restartPolicy: OnFailure
