apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
spec:
  selector:
    matchLabels:
      app: redis-commander
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      containers:
        - name: redis-commander
          image: rediscommander/redis-commander:latest
          env:
            - name: REDIS_HOSTS
              value: "local:redis:6379"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander
spec:
  selector:
    app: redis-commander
  ports:
    - port: 8081
      targetPort: 8081
