apiVersion: v1
kind: Secret
metadata:
  name: telellm-secrets
type: Opaque
stringData:
  BOT_TOKEN: "<BOT_TOKEN>"
  USER_IDS: "12345,67890"
  GROUP_IDS: "-12345,-67890"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telellm-config
data:
  LOG_LEVEL: "DEBUG"
  MODEL_NAME: "llama3.2"
